# Generated by Django 3.2.8 on 2025-11-03 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=100, verbose_name='接口标识')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('allowed_identities', models.CharField(default='OWNER,PROPERTY,MERCHANT,ADMIN', max_length=200, verbose_name='允许身份列表')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '接口权限',
                'verbose_name_plural': '接口权限',
                'db_table': 'ApiPermission',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('icon_name', models.CharField(blank=True, default='', max_length=100, verbose_name='图标名称')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=32, unique=True, verbose_name='物业ID')),
                ('property_name', models.CharField(max_length=200, verbose_name='物业名称')),
                ('community_name', models.CharField(blank=True, default='', max_length=200, verbose_name='社区名称')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物业信息',
                'verbose_name_plural': '物业信息',
                'db_table': 'PropertyProfile',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=32, unique=True, verbose_name='系统编号')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='OpenID')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=512, verbose_name='头像URL')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='手机号')),
                ('identity_type', models.CharField(choices=[('OWNER', '业主'), ('PROPERTY', '物业'), ('MERCHANT', '商户'), ('ADMIN', '管理员')], max_length=20, verbose_name='身份类型')),
                ('daily_points', models.IntegerField(default=0, verbose_name='当日积分')),
                ('total_points', models.IntegerField(default=0, verbose_name='累计积分')),
                ('daily_points_date', models.DateField(blank=True, null=True, verbose_name='当日积分日期')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('owner_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='wxcloudrun.propertyprofile', verbose_name='所属物业')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_profile', to='wxcloudrun.userinfo', verbose_name='关联用户'),
        ),
        migrations.CreateModel(
            name='PointsThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_points', models.IntegerField(default=0, verbose_name='最小积分')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_threshold', to='wxcloudrun.propertyprofile', verbose_name='物业')),
            ],
            options={
                'verbose_name': '积分阈值',
                'verbose_name_plural': '积分阈值',
                'db_table': 'PointsThreshold',
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='积分变动值')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to='wxcloudrun.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'db_table': 'PointsRecord',
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=32, unique=True, verbose_name='商户ID')),
                ('merchant_name', models.CharField(max_length=200, verbose_name='商户名称')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('banner_urls', models.TextField(blank=True, default='', verbose_name='轮播图URL(逗号分隔)')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='地址')),
                ('positive_rating_percent', models.IntegerField(default=0, verbose_name='好评率(%)')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxcloudrun.category', verbose_name='分类')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to='wxcloudrun.userinfo', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '商户信息',
                'verbose_name_plural': '商户信息',
                'db_table': 'MerchantProfile',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='Category_name_476266_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apipermission',
            unique_together={('endpoint_name', 'method')},
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['openid'], name='UserInfo_openid_6685cc_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['identity_type'], name='UserInfo_identit_d19fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyprofile',
            index=models.Index(fields=['property_id'], name='PropertyPro_propert_07ee04_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsrecord',
            index=models.Index(fields=['user'], name='PointsRecor_user_id_23c226_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['merchant_id'], name='MerchantPro_merchan_715cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['merchant_name'], name='MerchantPro_merchan_53d27f_idx'),
        ),
    ]
